---
title: "Lab 1"
author: "Group 12"
date: "2/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RCurl)
```

## Build a Book


## Weather Station

```{r, include=FALSE}
# Download the file ushcn-v2.5-stations.txt from the FTP site ftp://ftp.ncdc.noaa.gov/pub/data/ushcn/v2.5:

# Url of FTP site and name of file to download
URL      <- "ftp://ftp.ncdc.noaa.gov/pub/data/ushcn/v2.5/ushcn-v2.5-stations.txt"
# Name of file. If no folder is specified, the file will be saved in the working directory.
destfile <- "ushcn-v2.5-stations.txt"
download.file(URL, destfile)
```

```{r, include=FALSE}
# Read the weather data
weather <- read_fwf("ushcn-v2.5-stations.txt",
                    col_positions = fwf_positions(start = c(1, 3, 4, 6, 13, 22, 33, 39, 42, 73, 80, 87, 94), end = c(2, 3, 5, 11, 20, 30, 37, 40, 71, 78, 85, 92, 95), col_names = c("COUNTRY CODE", "NETWORK CODE ", "ID PLACEHOLDERS", "COOP ID", "LATITUDE", "LONGITUDE", "ELEVATION", "STATE", "NAME", "COMPONENT 1", "COMPONENT 2", "COMPONENT 3", "UTC OFFSET")))

weather <- weather %>%
  mutate(ELEVATION = as.numeric(ELEVATION))

usa <- map_data("state")

statename <- data.frame(STATE = state.abb, region = tolower(state.name), stringsAsFactors = FALSE)

usa <- usa %>% 
  left_join(statename, by = "region") %>%
  left_join(unique(weather[c("STATE", "UTC OFFSET")]), by = "STATE")
```

```{r echo=FALSE}
theme_set(theme_light())

weather %>%
  ggplot(aes(x = LONGITUDE, y = LATITUDE, fill = `UTC OFFSET`)) + 
  geom_polygon(data = usa, aes(x = long, y = lat, group = group)) +
  geom_path(data = usa, aes(x = long, y = lat, group = group), alpha = 0.3) +
  geom_point(aes(colour = ELEVATION)) + 
  scale_fill_gradient(low = "pink", high = "yellow") +
  ggtitle("Stations, Elevation and Time Zone") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20))
# Some states have two "UTC OFFSET" values, so the time zone may not be exactly true
```



## More Weather Data
```{r, include=FALSE}
# Url of FTP site and name of gz file to download
URL      <- "ftp://ftp.ncdc.noaa.gov/pub/data/ushcn/v2.5/ushcn.tavg.latest.raw.tar.gz"
# Name of gz file. If no folder is specified, the file will be saved in the working directory.
destfile <- "ushcn.tavg.latest.raw.tar.gz"
download.file(URL, destfile)
```

```{r, echo=FALSE}
# Create a folder called TavgLatestRaw. The gz file will be unzipped in this folder.
TavgLatestRawFolder <- "TavgLatestRaw"
dir.create(TavgLatestRawFolder)

# Unzip the gz file. This will create a folder "ushcn something-something" within the TavgLatestRaw folder. This newest folder will contains the unzipped files.
untar("ushcn.tavg.latest.raw.tar.gz", exdir=TavgLatestRawFolder) 

# Get the name of the new folder "ushcn something-something"
UnzippedFolder <- list.files(TavgLatestRawFolder)

# Change the working directory to the folder TavgLatestRaw
setwd(TavgLatestRawFolder)

# read file names of the unzipped files in "ushcn something-something"
files <-dir(UnzippedFolder)

# count the number of files 
numfiles <- length(files)
```
The file ushcn.tavg.latest.raw.tar.gz downloaded from ftp://ftp.ncdc.noaa.gov/pub/data/ushcn/v2.5  contains `r numfiles` files.

